// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as App$RescriptReactIntro from "./components/app/App.bs.js";

import './style/global.styl'
;

var reactRoot = document.querySelector("#react");

if (!(reactRoot == null)) {
  ReactDom.render(React.createElement(App$RescriptReactIntro.make, {}), reactRoot);
}

export {
  
}
/*  Not a pure module */
